### ISSUE TITLE
Formato de salida del parser

### ISSUE THREAD

**Issue by wakumaku** [JaimeObregon/infoelectoral#3]
Holas!
Acabo de empezar a mirar el repositorio y a enterarme un poquito de la estructura de carpetas y  archivos.

He ejecutado el script para ver cómo funcionaba y he visto que la salida es un print_r del objeto de resultado.
Cómo utilizas ese output? Creo que sería interesante que el parser tuviera un output estándar, tipo CSV para facilitar el parseo y el consumo desde otras herramientas.

He hecho una prueba que convierte cualquier salida del parser a CSV pero no tengo claro si podría ser útil / necesario.

Aqui va la prueba:

https://github.com/JaimeObregon/infoelectoral/compare/master...wakumaku:CSV_ADAPTER?expand=1
![toCSV](https://user-images.githubusercontent.com/938022/88835772-0aa4cb00-d1d6-11ea-898d-c1a3f4334caf.gif)

**Comment by JaimeObregon** [comment]
Hola. Efectivamente `parse.php` devuelve la salida por `stdout` con un mero `print_r()`. Prueba con `list.php`, que sí devuelve los resultados como CSV. Y si tienes cualquier duda, me dices por aquí.

Dejo este *issue* abierto para documentar yo esto mejor, y de paseo hacer que `parse.php` devuelva el resultado también en formato CSV.

**Comment by wakumaku** [comment]
> Hola. Efectivamente `parse.php` devuelve la salida por `stdout` con un mero `print_r()`. Prueba con `list.php`, que sí devuelve los resultados como CSV. Y si tienes cualquier duda, me dices por aquí.
> 
> Dejo este _issue_ abierto para documentar yo esto mejor, y de paseo hacer que `parse.php` devuelva el resultado también en formato CSV.

🤦 genial xD el list.php se me ha pasado totalmente  por alto, asunto resuelto :) , gracias!

**Comment by JaimeObregon** [comment]
He documentado mejor la función de cada uno de los dos *scripts*:

- `parse.php` es para examinar manualmente cualquier fichero `.DAT`. Como hay varios formatos de ficheros `.DAT` no es natural definir un formato de exportación. Por esta razón, mantengo la salida legible por humanos (`print_r()`).

- `lists.php` exporta las listas electorales, ahora sí, en formato CSV (reutilizable).

Gracias, @wakumaku. Cierro este *issue*, pero reábrelo si así lo necesitas.
