### ISSUE TITLE
Portar a plataforma .NET.

### ISSUE THREAD

**Issue by dariodotnet** [JaimeObregon/infoelectoral#6]
Soy usuario de la plataforma .NET y me preguntaba si te parecería una buena opción tener el mismo proyecto disponible en dicha plataforma.

.NET tiene una gestión de dependencias basada en (NuGet)[https://www.nuget.org/] y esto podría promover el uso en proyectos que ofreciese aun más visibilidad y opciones por parte de la comunidad.

Salvo que la opción final sea consumir todo la información desde una API, creo que esto abre otro camino más para que la comunidad aporte y consuma todas las opciones disponibles de tu proyecto.

**Comment by JaimeObregon** [comment]
Hola, Darío. Este repositorio contiene **unos scripts de línea de comandos** que decodifican los datos oficiales y ofrecen una salida estructurada (CSV). No tiene un interfaz web, y por lo tanto no entiendo qué ventajas tendría portarlo a .NET. ¿Podrías detallar un poco más?

Mi idea es desarrollar ahora **un portal de información electoral**, que en este caso sí tendrá, naturalmente, una interfaz web. Este portal consumirá los datos generados por este repositorio y probablemente expondrá una API pública. No lo desarrollaré en .NET porque no soy usuario de Windows y mi preferencia tecnológica es otra, si bien soy de la opinión de que el *stack* tecnológico es poco importante y lo que de verdad importa es lo que se hace con él.

En cuanto a la gestión de paquetes, **este proyecto no tiene ninguna dependencia y tampoco es una librería reutilizable**, por lo que no veo interés a paquetizarlo y publicarlo en una plataforforma como `Nuget`, `Composer`, `npm`, `Bower`…

En realidad este proyecto tiene poco recorrido ya, porque ya satisface la función para la cual lo desarrollé. No es el caso del portal electoral que estoy ahora comenzando, que sí tendrá un recorrido más largo y en torno al cual sería bonito que se articulara una comunidad de colaboradores.

**Comment by dariodotnet** [comment]
Efectivamente, este proyecto es sólo un traductor de archivos para que el proyecto final vaya haciendo uso de éste cuando toque. Lo que yo me preguntaba es si la idea general del proyecto será exponer una API para que pueda ser consumida por el propio portal web o bien que todas las piezas estén disponibles en este u otros repositorios de código pero que interactuarán entre sí para conformar la API, transformación de datos a un esquema común y su posterior almacenamiento en base de datos.

En el caso de que todo vaya a ser gestionado con código abierto para un almacenamiento final en base de datos y que cada uno pueda ir montando una API con diferentes estrategias de consultas, ofrecer más plataformas sí tendría sentido, ya que permitiría a la comunidad adquirir todas las dependencias finales para la tecnología que corresponda.

Insisto que esto es partiendo de la base de que todo el proyecto pueda ser creado como un conjunto de librerías que permiten el análisis masivo de archivos desde cualquier plataforma soportada. Podría imaginar a alguien utilizando las librerías para crear una aplicación móvil que informe de todo lo que se pueda para su pueblo/demarcación/CCAA.

En el caso de intentar desarrollar algo así, es cuando tendría sentido tener la posibilidad de utilizarlo en las diferentes tecnologías.

**Comment by JaimeObregon** [comment]
> Lo que yo me preguntaba es si la idea general del proyecto será exponer una API para que pueda ser consumida por el propio portal web o bien que todas las piezas estén disponibles en este u otros repositorios de código pero que interactuarán entre sí para conformar la API, transformación de datos a un esquema común y su posterior almacenamiento en base de datos.

Aunque aún no tengo nada completamente decidido, mi idea es hacer ambas cosas:

1. **Un portal web** (*frontend*) **y una API** (*backend*). El portal web consumirá los servicios de la API, pero estos servicios serían públicos y herramientas de terceros podrán consumirlos.

    Es la misma arquitectura que empleé en [contratosdecantabria.es][https://contratosdecantabria.es], donde el portal público consulta [una API que también es pública](https://redocly.github.io/redoc/?url=https://api.contratosdecantabria.es/docs#tag/Otros/paths/~1countdown/get) y [está abierta para que otros puedan también explotarla](https://contratosdecantabria.es/wtf/#api).

2. **Publicar todos los componentes como software libre**. Este repositorio (`infoelectoral`) es el primero.

Insisto en que todavía no estoy absolutamente seguro de que vaya a ser así, pero es lo más probable ahora mismo.

> En el caso de que todo vaya a ser gestionado con código abierto para un almacenamiento final en base de datos y que cada uno pueda ir montando una API con diferentes estrategias de consultas, ofrecer más plataformas sí tendría sentido, ya que permitiría a la comunidad adquirir todas las dependencias finales para la tecnología que corresponda.

Entiendo. **Ahora mismo no tengo una respuesta.** Mi intención es desarrollar el portal, publicar todo el código fuente y publicar también una API como servicio. No tengo ninguna objeción a que alguien haga un *fork* portado a .NET, teniéndose en cuenta los términos de la licencia, pero me parece pronto para hacerlo porque el proyecto está todavía en una fase muy inicial.

> Podría imaginar a alguien utilizando las librerías para crear una aplicación móvil que informe de todo lo que se pueda para su pueblo/demarcación/CCAA.

Sí; es un escenario interesante y trataré de facilitarlo todo lo posible.

Muchas gracias, @dariodotnet. Espero haber respondido a tu duda. Si es así, siéntete libre de cerrar el *issue*, y en caso contrario dime y seguimos debatiéndolo. 🙂
